### PR TITLE
Extra region clarification

### PR DESCRIPTION
**Pull request by fm360**
When selecting the region, I added the region codes next to the name of the region. For example: "USA" now displays as "USA (NTSC-U)" when selecting the region. I also clarified that EUR and AUS are the exact same region.

### CODE REVIEW

**Comment by ghost** [comment]
I don't think PAL or NTSC makes much sense to me here. I think they're usually used for TV / Video standards not portable gaming devices, smartphones, tablets or PC's. Granted I'm not entirely sure if I'm correct so hopefully someone who knows more can chime in

**Comment by fm360** [comment]
PAL and NTSC are also used to define a console's region. I did this for people who would like to know the region id's. It just clarifies what games will work with the region setting and what games won't. It also clarifies that Australia and Europe have the same region id and it doesn't matter which one you pick.

**Comment by fm360** [comment]
Just a little edit: this only applies to Nintendo consoles.

**Comment by profi200** [comment]
PAL and NTSC are completely irrelevant for the 3DS because it uses digital video signals. They are just completely outdated analog TV signal standards. People need to accept that these don't exist anymore.

**Comment by smealum** [comment]
i agree that this is unnecessary, NTSC/PAL has no meaning here. i also fail to see how it would be helpful here.

**Comment by NULLx76** [comment]
It may be useful to show that EUR and EU are the same but I don't see why adding NTSC or PAL would be useful and/or helpful

**Pull request closed without merging**
